package engine

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/arcships/open-doc-cli/internal/adapter"
)

// DBIndexFileName is the machine-generated row index that heads every Notion
// database directory. Like INDEX.md it is regenerated every sync, is
// not a mirrored page, and is never tracked in the manifest — so it never
// confuses delete reconciliation or the INDEX tree. The reserved-name rule
// (naming.reserved) prevents any row title from slugging to "_index", so a row
// can never collide with it.
const DBIndexFileName = "_index.md"

// maxIndexColumns caps how many property columns the row index shows beyond the
// title, keeping the table readable; the row files carry the full property set.
const maxIndexColumns = 4

// dbGeneratedMarker heads every generated `_index.md` so a reader (and a diff)
// knows it is machine-generated and must not be hand-edited.
const dbGeneratedMarker = "<!-- opendoc:generated by opendoc sync — do not edit by hand -->"

// generateDBIndex writes the `_index.md` row index into a database node's
// directory. It is deterministic (rows sorted by title then id, columns sorted by
// name) so a rerun with the same data is byte-stable.
func (e *Engine) generateDBIndex(n *treeNode, rc *runContext) error {
	content := renderDBIndex(n, rc)
	abs := filepath.Join(e.layout.Root, filepath.FromSlash(n.dirPath), DBIndexFileName)
	return atomicWrite(abs, []byte(content))
}

// indexRow is one rendered row of a database's `_index.md`.
type indexRow struct {
	title string
	id    string
	link  string            // link destination relative to the index file
	props map[string]string // rendered property values by name
}

// renderDBIndex builds the full `_index.md` content for a database node: a
// generated-file header, the database title, an optional online link, and a
// table with one row per database row (title linked to the row's local file plus
// a few key property columns).
func renderDBIndex(n *treeNode, rc *runContext) string {
	indexRel := filepath.ToSlash(filepath.Join(n.dirPath, DBIndexFileName))

	var rows []indexRow
	colSet := map[string]bool{}
	var columns []string
	for _, c := range n.children {
		if c.doc.Type != adapter.TypeDBRow {
			continue
		}
		r := indexRow{title: c.doc.Title, id: c.doc.ID, props: map[string]string{}}
		if c.bodyPath != "" {
			r.link = relAsset(indexRel, c.bodyPath)
		}
		if rp, ok := rc.rowProps[c.doc.ID]; ok {
			for _, e := range rp.Entries {
				r.props[e.Key] = e.Value
				if !colSet[e.Key] {
					colSet[e.Key] = true
					columns = append(columns, e.Key)
				}
			}
		}
		rows = append(rows, r)
	}

	sort.Strings(columns)
	if len(columns) > maxIndexColumns {
		columns = columns[:maxIndexColumns]
	}
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].title != rows[j].title {
			return rows[i].title < rows[j].title
		}
		return rows[i].id < rows[j].id
	})

	var b strings.Builder
	b.WriteString(dbGeneratedMarker + "\n")
	title := n.doc.Title
	if title == "" {
		title = "Database"
	}
	b.WriteString("# " + title + "\n\n")
	if n.doc.URL != "" {
		b.WriteString("> Online database: " + n.doc.URL + "\n\n")
	}
	b.WriteString(fmt.Sprintf("> %d rows total\n\n", len(rows)))

	if len(rows) == 0 {
		b.WriteString("_(no rows yet)_\n")
		return b.String()
	}

	b.WriteString("| Title")
	for _, col := range columns {
		b.WriteString(" | " + cell(col))
	}
	b.WriteString(" |\n|---")
	for range columns {
		b.WriteString("|---")
	}
	b.WriteString("|\n")

	for _, r := range rows {
		b.WriteString("| " + titleCell(r))
		for _, col := range columns {
			b.WriteString(" | " + cell(r.props[col]))
		}
		b.WriteString(" |\n")
	}
	return b.String()
}

// titleCell renders a row's title cell: a Markdown link to the row's local file,
// or bold text when the row has no body file (defensive — rows always do).
func titleCell(r indexRow) string {
	text := cell(r.title)
	if text == "" {
		text = cell(r.id)
	}
	if r.link == "" {
		return "**" + text + "**"
	}
	return "[" + text + "](" + mdLinkDest(r.link) + ")"
}

// cell escapes a value for a Markdown table cell: pipes are escaped and newlines
// folded to spaces so a multi-line/rich value never breaks the table.
func cell(s string) string {
	s = strings.ReplaceAll(s, "\r\n", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "\r", " ")
	s = strings.ReplaceAll(s, "|", "\\|")
	return escapeLinkText(s)
}
