package engine

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/arcships/open-doc-cli/internal/adapter"
	"github.com/arcships/open-doc-cli/internal/manifest"
)

// IndexFileName is the mirror-root index map regenerated at the end of every
// sync; it is the retrieval layer's entry point (see docs/dev/architecture.md).
const IndexFileName = "INDEX.md"

// generateIndex regenerates INDEX.md at the mirror root from the manifest's
// active documents. It is the last finalize step of a sync and
// runs once across all platforms. syncedAt is stamped into the header. The file
// is not tracked in the manifest, so regenerating it never makes any document
// look dirty.
func (e *Engine) generateIndex(db *manifest.DB, syncedAt time.Time) error {
	docs, err := db.ListActiveDocuments()
	if err != nil {
		return err
	}
	content := renderIndex(docs, syncedAt)
	return atomicWrite(filepath.Join(e.layout.Root, IndexFileName), []byte(content))
}

// indexEntry is one line of the INDEX tree: a document or a structural folder.
type indexEntry struct {
	sortKey  []string // path segments used for deterministic tree ordering
	depth    int      // number of segments (indentation basis)
	title    string
	link     string // relative link target; "" for a folder (no body)
	updated  string // remote edit time; "" when unknown
	platform string
}

// renderIndex builds the full INDEX.md content: a library-level header followed
// by the directory tree. Ordering is deterministic (segment-wise path sort),
// independent of the manifest row order.
func renderIndex(docs []manifest.Document, syncedAt time.Time) string {
	entries := make([]indexEntry, 0, len(docs))
	perPlatform := map[string]int{}
	total := 0
	for _, d := range docs {
		if d.LocalPath == "" {
			continue
		}
		e := entryForDoc(d)
		entries = append(entries, e)
		if e.link != "" {
			perPlatform[d.Platform]++
			total++
		}
	}

	sort.Slice(entries, func(i, j int) bool { return lessSegments(entries[i].sortKey, entries[j].sortKey) })

	minDepth := 0
	for i, e := range entries {
		if i == 0 || e.depth < minDepth {
			minDepth = e.depth
		}
	}

	var b strings.Builder
	writeIndexHeader(&b, syncedAt, total, perPlatform)
	b.WriteString("## Contents\n\n")
	if len(entries) == 0 {
		b.WriteString("_(no documents yet)_\n")
		return b.String()
	}
	for _, e := range entries {
		indent := strings.Repeat("  ", e.depth-minDepth)
		if e.link != "" {
			b.WriteString(fmt.Sprintf("%s- [%s](%s)", indent, escapeLinkText(e.title), mdLinkDest(e.link)))
		} else {
			b.WriteString(fmt.Sprintf("%s- **%s**", indent, escapeLinkText(e.title)))
		}
		if e.updated != "" {
			b.WriteString(" · " + e.updated)
		}
		b.WriteByte('\n')
	}
	return b.String()
}

// entryForDoc computes the INDEX entry for a manifest document. A README body
// collapses onto its directory (the directory's page is the README), a leaf
// document sorts by its extension-stripped path, and a folder is a structural,
// unlinked line.
func entryForDoc(d manifest.Document) indexEntry {
	lp := filepath.ToSlash(d.LocalPath)
	e := indexEntry{title: d.Title, updated: d.RemoteEdited, platform: d.Platform}
	switch {
	case d.Type == string(adapter.TypeFolder):
		e.sortKey = strings.Split(lp, "/")
		e.link = "" // folders have no body to link to
	case d.Type == string(adapter.TypeDB):
		// A database is a directory; its browsable entry is the generated row
		// index, so link there (the rows appear nested beneath it).
		e.sortKey = strings.Split(lp, "/")
		e.link = lp + "/" + DBIndexFileName
	case strings.HasSuffix(lp, "/README.md") || lp == "README.md":
		dir := strings.TrimSuffix(strings.TrimSuffix(lp, "README.md"), "/")
		e.sortKey = splitNonEmpty(dir)
		e.link = lp
	default:
		e.sortKey = strings.Split(strings.TrimSuffix(lp, ".md"), "/")
		e.link = lp
	}
	e.depth = len(e.sortKey)
	// Untitled remote documents carry an empty title; fall back to the on-disk
	// name (naming already made it unique/legible) so the entry is never blank.
	if e.title == "" && len(e.sortKey) > 0 {
		e.title = e.sortKey[len(e.sortKey)-1]
	}
	return e
}

// writeIndexHeader writes the library-level metadata block: what this
// is, the read-only red line, the last sync time, and per-platform doc counts.
func writeIndexHeader(b *strings.Builder, syncedAt time.Time, total int, perPlatform map[string]int) {
	b.WriteString("# opendoc Knowledge Base Index\n\n")
	b.WriteString("> Read-only mirror: this is a local copy of your Notion / Feishu documents. Do not edit here; to change content, follow each document's frontmatter `url` and edit it online.\n")
	b.WriteString("> This file is generated by `opendoc sync`. Do not edit by hand.\n\n")
	b.WriteString("- Last synced: " + syncedAt.UTC().Format(time.RFC3339) + "\n")
	b.WriteString(fmt.Sprintf("- Total documents: %d\n", total))
	platforms := make([]string, 0, len(perPlatform))
	for p := range perPlatform {
		platforms = append(platforms, p)
	}
	sort.Strings(platforms)
	for _, p := range platforms {
		b.WriteString(fmt.Sprintf("  - %s: %d\n", p, perPlatform[p]))
	}
	b.WriteString("\n")
}

// lessSegments compares two path-segment slices lexicographically, so entries
// sort into a stable depth-first tree order.
func lessSegments(a, b []string) bool {
	for i := 0; i < len(a) && i < len(b); i++ {
		if a[i] != b[i] {
			return a[i] < b[i]
		}
	}
	return len(a) < len(b)
}

// splitNonEmpty splits a slash path into segments, returning an empty slice for
// the empty string (rather than [""]).
func splitNonEmpty(p string) []string {
	if p == "" {
		return nil
	}
	return strings.Split(p, "/")
}

// escapeLinkText escapes the characters that would break Markdown link text.
func escapeLinkText(s string) string {
	r := strings.NewReplacer("[", "\\[", "]", "\\]")
	return r.Replace(s)
}

// mdLinkDest renders a relative path as a Markdown link destination, wrapping it
// in angle brackets when it contains spaces or parentheses (which would
// otherwise terminate the destination). Naming already strips '<' and '>' from
// titles, so angle-bracket wrapping is always safe.
func mdLinkDest(p string) string {
	if strings.ContainsAny(p, " ()") {
		return "<" + p + ">"
	}
	return p
}
